# Generated by Django 6.0.7 on 2026-07-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CIV', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('COM', 'Computer Engineering'), ('MEC', 'Mechanical Engineering'), ('ARC', 'Architecture'), ('APP', 'Applied Sciences'), ('CIT', 'IT Support'), ('FIN', 'Finance'), ('ACA', 'Academic Affairs'), ('LIB', 'Library'), ('FAC', 'Facilities')], max_length=3, null=True),
        ),
    ]
