# Generated by Django 6.0.7 on 2026-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, help_text='User/Staff escalation level (e.g. Level 1, Level 2, Level 3)'),
        ),
    ]
