# Generated by Django 6.0.7 on 2026-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, default=1, help_text='Staff escalation level (Level 1, 2, 3). Only applies to staff and administrator roles.', null=True),
        ),
    ]
