# Generated by Django 6.0.7 on 2026-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('LAB', 'Lab Technician'), ('TEACHER', 'Teacher / Professor'), ('IT', 'IT Support'), ('FINANCE', 'Finance Staff'), ('ACADEMIC', 'Academic Staff'), ('LIBRARY', 'Library Staff'), ('FACILITIES', 'Facilities Staff')], help_text='For staff: specialization for routing', max_length=20, null=True),
        ),
    ]
