# Generated by Django 6.0.7 on 2026-08-24 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, help_text='Escalation hierarchy level (auto-derived from role): 0 = staff, 1 = team lead, 2 = department HOD; campus admins sit above the chain.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('CR', 'Class Representative'), ('STAFF', 'Staff'), ('TEAM_LEAD', 'Team Lead'), ('DEPT_ADMIN', 'Dept Admin (HOD)'), ('CAMPUS_ADMIN', 'Campus Admin')], default='STUDENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('LAB', 'Lab Technician'), ('TEACHER', 'Teacher / Professor'), ('IT', 'IT Support'), ('FINANCE', 'Finance Staff'), ('ACADEMIC', 'Academic Staff'), ('LIBRARY', 'Library Staff'), ('FACILITIES', 'Facilities Staff')], help_text='For staff: specialization metadata', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('CIV', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('COM', 'Computer Engineering'), ('MEC', 'Mechanical Engineering'), ('ARC', 'Architecture'), ('APP', 'Applied Sciences'), ('CIT', 'IT Support'), ('FIN', 'Finance'), ('ACA', 'Academic Affairs'), ('LIB', 'Library'), ('FAC', 'Facilities')], max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(blank=True, help_text="Team lead this team's tickets are routed to", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sub-department (Team)',
                'verbose_name_plural': 'Sub-departments (Teams)',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='sub_department',
            field=models.ForeignKey(blank=True, help_text='Team/sub-department this staff member belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.subdepartment'),
        ),
        migrations.AddConstraint(
            model_name='subdepartment',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_team_per_department'),
        ),
    ]
