# Generated by Django 6.0.7 on 2026-08-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remap_staff_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='staff_type',
        ),
    ]
