# Generated by Django 6.0.7 on 2026-08-24 10:06

from django.db import migrations, models

DEFAULT_DEPARTMENTS = [
    ("CIV", "Civil Engineering"),
    ("ELE", "Electrical Engineering"),
    ("COM", "Computer Engineering"),
    ("MEC", "Mechanical Engineering"),
    ("ARC", "Architecture"),
    ("APP", "Applied Sciences"),
    ("CIT", "IT Support"),
    ("FIN", "Finance"),
    ("ACA", "Academic Affairs"),
    ("LIB", "Library"),
    ("FAC", "Facilities"),
]


def seed_departments(apps, schema_editor):
    Department = apps.get_model("accounts", "Department")
    for code, name in DEFAULT_DEPARTMENTS:
        Department.objects.get_or_create(code=code, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_staff_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_departments, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subdepartment',
            name='department',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
