# Generated by Django 6.0.7 on 2026-07-20 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Use placeholders: {ticket_id}, {title}, {status}, {assignee}')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ESCALATION', 'Escalation'), ('REASSIGNMENT', 'Reassignment'), ('DEADLINE_WARNING', 'Deadline Warning'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ESCALATION', 'Escalation'), ('REASSIGNMENT', 'Reassignment'), ('DEADLINE_WARNING', 'Deadline Warning'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tickets.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
