# Generated by Django 6.0.7 on 2026-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('REPLY', 'Reply'), ('STATUS_CHANGE', 'Status Change'), ('ESCALATION', 'Escalation'), ('REASSIGNMENT', 'Reassignment'), ('DEADLINE_WARNING', 'Deadline Warning'), ('SYSTEM', 'System')], max_length=30, unique=True)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['notification_type'],
            },
        ),
    ]
