# Generated by Django 6.0.7 on 2026-08-08 17:31

from django.db import migrations, models


def enable_email_defaults(apps, schema_editor):
    NotificationSetting = apps.get_model("notifications", "NotificationSetting")
    NotificationSetting.objects.update(email=True)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_seed_notification_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='email',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(enable_email_defaults, migrations.RunPython.noop),
    ]
