# Generated by Django 6.0.7 on 2026-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationsetting_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
        migrations.DeleteModel(
            name='NotificationTemplate',
        ),
    ]
