# Generated by Django 6.0.7 on 2026-07-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='target_department',
            field=models.CharField(choices=[('SELF', "Ticket's Own Department"), ('CIT', 'CIT Team'), ('ACADEMIC', 'Academic Section'), ('FINANCE', 'Financial Team'), ('HOD', 'Respective HOD'), ('LIBRARY', 'Library Staff'), ('FACILITIES', 'Facilities Team'), ('CAMPUS_ADMIN', 'Campus Admin')], default='SELF', max_length=20),
        ),
    ]
