# Generated by Django 6.0.7 on 2026-07-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_routingrule_target_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingrule',
            name='target_department',
            field=models.CharField(choices=[('SELF', "Ticket's Own Department"), ('CIT', 'CIT (IT Support)'), ('FIN', 'Finance'), ('ACA', 'Academic Affairs'), ('LIB', 'Library'), ('FAC', 'Facilities'), ('HOD', 'Respective HOD'), ('CAMPUS_ADMIN', 'Campus Admin')], default='SELF', max_length=20),
        ),
    ]
