# Generated by Django 6.0.7 on 2026-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_routingrule_target_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_two_way_escalation', models.BooleanField(default=True, help_text='Allow de-escalation/handback of escalated tickets')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
            },
        ),
    ]
