# Generated by Django 6.0.7 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_current_support_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='on_hold',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='on_hold_since',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_pause_reason',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_paused_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sla_paused_minutes',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='waiting_for_customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='waiting_since',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('OK', 'OK'), ('APPROACHING', 'Approaching SLA'), ('BREACHED', 'SLA Breached')], default='OK', max_length=20),
        ),
    ]
