# Generated by Django 6.0.7 on 2026-08-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_on_hold_remove_ticket_on_hold_since_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Reply/thread message this attachment belongs to (blank = attached to the ticket itself)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticketmessage'),
        ),
    ]
