# Generated by Django 6.0.7 on 2026-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0009_alter_escalationpolicy_category'),
        ('tickets', '0008_attachment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, help_text='Hardcoded category name (see tickets.categories)', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='RoutingRule',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
