# Generated by Django 6.0.7 on 2026-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_category_delete_routingrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Hardcoded category name (see tickets.categories)', max_length=100, unique=True)),
                ('sla_response_hours', models.IntegerField(default=24, help_text='Target response time in hours')),
                ('sla_resolution_hours', models.IntegerField(default=72, help_text='Target resolution time in hours')),
            ],
            options={
                'verbose_name': 'Category SLA',
                'verbose_name_plural': 'Category SLAs',
            },
        ),
    ]
