# Generated by Django 6.0.7 on 2026-08-24 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_level_alter_user_role_and_more'),
        ('tickets', '0010_categorysla'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sub_department',
            field=models.ForeignKey(blank=True, help_text='Team/sub-department handling this ticket (resolved from the category route)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='accounts.subdepartment'),
        ),
    ]
