# Generated by Django 6.0.7 on 2026-08-24 10:06

from django.db import migrations, models

DEFAULT_CATEGORIES = [
    ("Lab Equipment", "Lab hardware, equipment, projector issues"),
    ("Classroom", "Classroom, teaching aid, whiteboard issues"),
    ("Network / Internet", "Campus internet, WiFi, network issues"),
    ("Financial / Fees", "Payments, scholarships, refunds, fees"),
    ("Academic", "Grades, registration, transcripts, exams"),
    ("Library", "Library services, book issues"),
    ("Hostel / Facilities", "Hostel, accommodation, maintenance"),
    ("General / Other", "Other issues"),
]


def seed_categories(apps, schema_editor):
    """Create the default categories and merge any CategorySla overrides
    before the old model is removed."""
    TicketCategory = apps.get_model("tickets", "TicketCategory")
    CategorySla = apps.get_model("tickets", "CategorySla")

    for name, description in DEFAULT_CATEGORIES:
        TicketCategory.objects.get_or_create(
            name=name, defaults={"description": description}
        )

    for row in CategorySla.objects.all():
        cat = TicketCategory.objects.filter(name=row.category).first()
        if cat is None:
            cat = TicketCategory.objects.create(name=row.category)
        cat.sla_response_hours = row.sla_response_hours
        cat.sla_resolution_hours = row.sla_resolution_hours
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_ticket_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sla_response_hours', models.IntegerField(default=24, help_text='Target response time in hours')),
                ('sla_resolution_hours', models.IntegerField(default=72, help_text='Target resolution time in hours')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='CategorySla',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, help_text='Dynamic category name (decides SLA hours only)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
