# Generated by Django 6.0.7 on 2026-08-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0004_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('is_recurring_annual', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SupportLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Lower order = lower level')),
                ('department', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('day',)},
            },
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, help_text='Restrict policy to a department (blank = all)', max_length=3, null=True)),
                ('priority', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Restrict policy to a priority (blank = all)', max_length=10, null=True)),
                ('response_sla_hours', models.PositiveIntegerField(default=4)),
                ('resolution_sla_hours', models.PositiveIntegerField(default=24)),
                ('business_hours_only', models.BooleanField(default=False, help_text='Calculate SLA only within configured business hours')),
                ('notify_assigned_50', models.BooleanField(default=True)),
                ('notify_assigned_75', models.BooleanField(default=True)),
                ('notify_assigned_custom', models.BooleanField(default=False)),
                ('notify_assigned_custom_pct', models.PositiveSmallIntegerField(blank=True, help_text='1-99', null=True)),
                ('notify_manager_50', models.BooleanField(default=False)),
                ('notify_manager_75', models.BooleanField(default=True)),
                ('notify_manager_90', models.BooleanField(default=False)),
                ('notify_manager_100', models.BooleanField(default=False)),
                ('notify_manager_custom', models.BooleanField(default=False)),
                ('notify_manager_custom_pct', models.PositiveSmallIntegerField(blank=True, help_text='1-99', null=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False, help_text='SMS support (future ready)')),
                ('auto_escalate', models.BooleanField(default=False)),
                ('escalation_delay_minutes', models.PositiveIntegerField(default=60, help_text='0 = immediately after breach')),
                ('auto_assign_action', models.CharField(choices=[('DO_NOTHING', 'Do Nothing'), ('NOTIFY_ONLY', 'Notify Only'), ('ADD_TO_ESCALATION_QUEUE', 'Add To Escalation Queue'), ('AUTO_ASSIGN_LEVEL', 'Auto Assign Level'), ('AUTO_ASSIGN_TEAM', 'Auto Assign Specific Team'), ('AUTO_ASSIGN_USER', 'Auto Assign Specific User')], default='DO_NOTHING', max_length=30)),
                ('auto_assign_department', models.CharField(blank=True, help_text='Team (department) for AUTO_ASSIGN_TEAM', max_length=3, null=True)),
                ('increase_priority_on_breach', models.BooleanField(default=False)),
                ('priority_mapping', models.JSONField(blank=True, default=dict, help_text='e.g. {"LOW": "MEDIUM", "MEDIUM": "HIGH", "HIGH": "CRITICAL", "CRITICAL": "CRITICAL"}')),
                ('escalate_critical_immediately', models.BooleanField(default=False)),
                ('ignore_sla_waiting_customer', models.BooleanField(default=False)),
                ('pause_during_holidays', models.BooleanField(default=True)),
                ('pause_outside_business_hours', models.BooleanField(default=False)),
                ('pause_when_on_hold', models.BooleanField(default=True)),
                ('auto_assign_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Restrict policy to a category (blank = all)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='tickets.category')),
                ('auto_assign_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='escalations.supportlevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='escalations.escalationpolicy')),
            ],
            options={
                'ordering': ['policy', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupportQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=3, null=True)),
                ('is_escalation_queue', models.BooleanField(default=False, help_text='Designates the escalation queue used by auto-escalation')),
                ('is_active', models.BooleanField(default=True)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_queues', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='auto_assign_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='escalations.supportqueue'),
        ),
        migrations.CreateModel(
            name='TicketAssignmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_stages', to='escalations.supportqueue')),
                ('support_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_stages', to='escalations.supportlevel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_stages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('POLICY_APPLIED', 'Policy Applied'), ('NOTIFICATION_SENT', 'Notification Sent'), ('ESCALATED', 'Escalated'), ('DE_ESCALATED', 'De-Escalated'), ('PRIORITY_CHANGED', 'Priority Changed'), ('QUEUE_CHANGED', 'Queue Changed'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('SLA_PAUSED', 'SLA Paused'), ('SLA_RESUMED', 'SLA Resumed'), ('SLA_BREACHED', 'SLA Breached'), ('RULE_APPLIED', 'Rule Applied'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('key', models.CharField(blank=True, help_text='Deduplication key (e.g. notify:assigned:50)', max_length=120, null=True)),
                ('message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_history', to='tickets.ticket')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='escalations.escalationpolicy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', 'action'], name='escalations_ticket__f86d95_idx'), models.Index(fields=['key'], name='escalations_key_add091_idx')],
            },
        ),
    ]
