# Generated by Django 6.0.7 on 2026-08-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHours',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='business_hours_only',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='pause_during_holidays',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='pause_outside_business_hours',
        ),
    ]
