# Generated by Django 6.0.7 on 2026-08-06 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0002_delete_businesshours_delete_holiday_and_more'),
        ('tickets', '0005_ticket_current_support_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='auto_assign_level',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='resolution_sla_hours',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='response_sla_hours',
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='from_level',
            field=models.ForeignKey(blank=True, help_text='Escalate tickets currently at this level (blank = any level)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies_from', to='escalations.supportlevel'),
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='to_level',
            field=models.ForeignKey(blank=True, help_text='Escalate tickets to this level (blank = next level after current)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies_to', to='escalations.supportlevel'),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='auto_assign_action',
            field=models.CharField(choices=[('AUTO_ASSIGN', 'Auto Assign (best available at level)'), ('NOTIFY_ONLY', 'Notify Only'), ('ADD_TO_ESCALATION_QUEUE', 'Add To Escalation Queue'), ('AUTO_ASSIGN_TEAM', 'Auto Assign Specific Team'), ('AUTO_ASSIGN_USER', 'Auto Assign Specific User')], default='AUTO_ASSIGN', max_length=30),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Restrict policy to a category (blank = all tickets)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_policies', to='tickets.category'),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='department',
            field=models.CharField(blank=True, help_text='Restrict policy to a department (blank = all tickets)', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='priority',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Restrict policy to a priority (blank = all tickets)', max_length=10, null=True),
        ),
    ]
