# Generated by Django 6.0.7 on 2026-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0004_remove_supportlevel_use_staff_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationpolicy',
            name='from_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 (Staff)'), (2, 'Level 2 (Staff)'), (3, 'Level 3 (Department HOD)')], help_text='Escalate tickets currently at this staff level (blank = any level)', null=True),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='to_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1 (Staff)'), (2, 'Level 2 (Staff)'), (3, 'Level 3 (Department HOD)')], help_text='Escalate tickets to this staff level (blank = next level after current)', null=True),
        ),
    ]
