# Generated by Django 6.0.7 on 2026-08-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0005_alter_escalationpolicy_from_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='auto_assign_action',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='auto_assign_department',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='auto_assign_queue',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='auto_assign_user',
        ),
    ]
