# Generated by Django 6.0.7 on 2026-08-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0006_remove_auto_assign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='ignore_sla_waiting_customer',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='pause_when_on_hold',
        ),
        migrations.AlterField(
            model_name='escalationhistory',
            name='action',
            field=models.CharField(choices=[('POLICY_APPLIED', 'Policy Applied'), ('NOTIFICATION_SENT', 'Notification Sent'), ('ESCALATED', 'Escalated'), ('DE_ESCALATED', 'De-Escalated'), ('PRIORITY_CHANGED', 'Priority Changed'), ('QUEUE_CHANGED', 'Queue Changed'), ('ASSIGNMENT_CHANGED', 'Assignment Changed'), ('SLA_BREACHED', 'SLA Breached'), ('RULE_APPLIED', 'Rule Applied'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30),
        ),
    ]
