# Generated by Django 6.0.7 on 2026-08-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0007_remove_escalationpolicy_ignore_sla_waiting_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportqueue',
            name='default_assignee',
        ),
    ]
