# Generated by Django 6.0.7 on 2026-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0008_remove_supportqueue_default_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationpolicy',
            name='category',
            field=models.CharField(blank=True, help_text='Restrict policy to a hardcoded category name (blank = all tickets)', max_length=100, null=True),
        ),
    ]
