# Generated by Django 6.0.7 on 2026-08-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0010_single_escalation_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationpolicy',
            name='from_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Level 0 (Staff)'), (1, 'Level 1 (Team Lead)'), (2, 'Level 2 (Department HOD)'), (3, 'Level 3 (Campus Admin)')], help_text='Escalate tickets currently at this staff level (blank = any level)', null=True),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='to_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Level 0 (Staff)'), (1, 'Level 1 (Team Lead)'), (2, 'Level 2 (Department HOD)'), (3, 'Level 3 (Campus Admin)')], help_text='Escalate tickets to this staff level (blank = next level after current)', null=True),
        ),
        migrations.AlterField(
            model_name='ticketassignmentstage',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Level 0 (Staff)'), (1, 'Level 1 (Team Lead)'), (2, 'Level 2 (Department HOD)'), (3, 'Level 3 (Campus Admin)')], help_text='Staff escalation level the ticket moved to', null=True),
        ),
    ]
