# Generated by Django 6.0.7 on 2026-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0012_remap_escalation_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalationpolicy',
            name='department',
            field=models.CharField(blank=True, help_text='Restrict policy to a department code (blank = all tickets)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportqueue',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
