# Generated by Django 6.0.7 on 2026-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0013_alter_escalationpolicy_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_assigned_50',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_assigned_75',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_assigned_custom',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_assigned_custom_pct',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_email',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_in_app',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_100',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_50',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_75',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_90',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_custom',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_manager_custom_pct',
        ),
        migrations.RemoveField(
            model_name='escalationpolicy',
            name='notify_sms',
        ),
    ]
